# Generated by Django 4.2.7 on 2023-11-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Course',
            name='camada',
            field=models.IntegerField(),
        ),
    ]
