# Generated by Django 4.2.7 on 2023-12-09 00:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0002_alter_curso_camada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trekking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('city', models.IntegerField(max_length=40)),
                ('content', models.IntegerField(max_length=40)),
                ('author', models.IntegerField(max_length=40)),
                ('creation_date', models.IntegerField(max_length=40)),
                ('avatar_trekking', models.ImageField(upload_to='Trekking')),
                ('date', models.DateField(default=datetime.datetime(2023, 12, 8, 21, 13, 4, 835263))),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('creation_date', models.IntegerField(max_length=40)),
                ('trekking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.trekking')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
