# Generated by Django 4.2.7 on 2023-12-09 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_trekking_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekking',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='creation_date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 8, 55, 27, 560066)),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
