# Generated by Django 4.2.7 on 2023-12-09 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_trekking_author_alter_trekking_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekking',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='trekking',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 9, 4, 40, 30914)),
        ),
    ]
