# Generated by Django 4.2.7 on 2023-12-12 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_trekking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 20, 14, 28, 438263)),
        ),
    ]
