# Generated by Django 4.2.7 on 2023-12-12 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_comments_creation_date_alter_trekking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 20, 16, 50, 773396)),
        ),
    ]
