# Generated by Django 4.2.7 on 2023-12-12 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_trekking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
