# Generated by Django 4.2.7 on 2023-12-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_delete_course_delete_entregable_delete_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekking',
            name='difficulty',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
