# Generated by Django 4.2.7 on 2023-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_trekking_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekking',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
